"""
render_claim_chain.py — Render a synthesis page's claim-chain into a draft thesis section.

Input: a synthesis slug.
Output: a markdown file under tmp/rendered/ that walks the chain and produces
        a paragraph for each citable claim.

Refusal logic: if any claim cited is below the synthesis's
`required-evidence-status:` threshold (e.g., `thesis-citable`), the renderer
prints which claim is blocking and exits non-zero. It does NOT silently render
incomplete chains.

Usage:
  python 06-scripts/render_claim_chain.py <synthesis-slug>
  python 06-scripts/render_claim_chain.py --check <synthesis-slug>   # dry-run
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

try:
    import frontmatter  # type: ignore
except ImportError:
    print("ERROR: install python-frontmatter: pip install python-frontmatter", file=sys.stderr)
    sys.exit(2)

VAULT_ROOT = Path(__file__).resolve().parent.parent
WIKI_DIR = VAULT_ROOT / "02-wiki"
OUT_DIR = VAULT_ROOT / "tmp" / "rendered"


def find_page(slug: str) -> Path | None:
    for p in WIKI_DIR.rglob(f"{slug}.md"):
        return p
    return None


def evidence_is_citable(meta: dict) -> tuple[bool, str]:
    t = meta.get("type")
    if t == "result":
        ok = bool(meta.get("can-cite-thesis"))
        return ok, "can-cite-thesis" if ok else f"result-status={meta.get('result-status')}, can-cite-thesis={meta.get('can-cite-thesis')}"
    if t == "paper":
        rs = meta.get("reading-status", "to-read")
        ev = meta.get("evidence-class")
        reading_ok = rs in {"read", "deep-read", "cited"}
        evidence_ok = ev not in (None, "", "ASSUMPTION")
        ok = reading_ok and evidence_ok
        if ok:
            return True, f"reading-status={rs}, evidence-class={ev}"
        return False, (f"not citable: reading-status={rs}, evidence-class={ev} — a paper backing a "
                       f"thesis claim needs reading-status in read/deep-read/cited AND a verified "
                       f"evidence-class (not empty/ASSUMPTION)")
    return True, f"type={t} (assumed citable)"


def render_synthesis(synthesis_slug: str, check_only: bool = False) -> int:
    syn_path = find_page(synthesis_slug)
    if not syn_path:
        print(f"Synthesis page [[{synthesis_slug}]] not found.", file=sys.stderr)
        return 1

    syn = frontmatter.load(syn_path)
    syn_meta = dict(syn.metadata)
    if syn_meta.get("type") != "synthesis":
        print(f"[[{synthesis_slug}]] is not type=synthesis (got {syn_meta.get('type')})", file=sys.stderr)
        return 1

    chain = syn_meta.get("claim-chain") or []
    if not chain:
        print(f"[[{synthesis_slug}]] has empty claim-chain.", file=sys.stderr)
        return 1

    threshold = syn_meta.get("required-evidence-status", "thesis-citable")

    blockers: list[str] = []
    rendered: list[str] = []

    for raw in chain:
        slug = str(raw).strip()
        if slug.startswith("[[") and slug.endswith("]]"):
            slug = slug[2:-2]
        slug = slug.split("|", 1)[0].split("#", 1)[0].strip()
        cp = find_page(slug)
        if not cp:
            blockers.append(f"  - [[{slug}]] — page not found")
            continue
        cmeta = dict(frontmatter.load(cp).metadata)
        if cmeta.get("type") != "claim":
            blockers.append(f"  - [[{slug}]] — not a claim (type={cmeta.get('type')})")
            continue
        if cmeta.get("claim-status") != "thesis-ready" and threshold == "thesis-citable":
            blockers.append(f"  - [[{slug}]] — claim-status={cmeta.get('claim-status')} (need thesis-ready)")
            continue

        for ev in cmeta.get("evidence-for", []) or []:
            ev_slug = str(ev).strip().lstrip("[").rstrip("]").split("|", 1)[0].strip()
            ep = find_page(ev_slug)
            if not ep:
                blockers.append(f"  - [[{slug}]] cites [[{ev_slug}]] — evidence page not found")
                continue
            emeta = dict(frontmatter.load(ep).metadata)
            ok, reason = evidence_is_citable(emeta)
            if not ok:
                blockers.append(f"  - [[{slug}]] cites [[{ev_slug}]] — not citable ({reason})")

        rendered.append(cmeta.get("paragraph-draft") or f"<!-- TODO: paragraph-draft missing for [[{slug}]] -->")

    if blockers:
        print(f"Renderer refuses to produce output for [[{synthesis_slug}]]:\n")
        for b in blockers:
            print(b)
        print("\nFix the blocking items above before rendering.")
        return 2

    if check_only:
        print(f"OK: [[{synthesis_slug}]] would render {len(rendered)} paragraph(s) cleanly.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"{synthesis_slug}.md"
    out_path.write_text(
        f"# Rendered from [[{synthesis_slug}]]\n\n"
        f"<!-- Auto-generated by render_claim_chain.py. Do not hand-edit. Re-render to refresh. -->\n\n"
        + "\n\n".join(rendered),
        encoding="utf-8",
    )
    print(f"Rendered to {out_path}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("synthesis", help="synthesis slug (filename without .md)")
    ap.add_argument("--check", action="store_true", help="dry-run; report blockers but don't write output")
    args = ap.parse_args()
    return render_synthesis(args.synthesis, check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
