"""Release-moment deposit receipt: hash once at a boundary, trust the receipt (E1/TU-2).

Closes failure-catalog item E1 (2026-08-20 team upgrade, director directive):
deposit root hashes were re-derived habitually — per report, over a mostly
unchanged artifact set — burning attention and churning the printed hash. The
policy this module encodes is TU-2 (03-verification-economics.md):

    Hash once at a boundary moment, record a receipt (hash + timestamp + what it
    covered), trust the receipt until the artifact set changes; never re-hash
    unchanged artifacts on a schedule or per report.

``build_manifest`` runs at deposit/release moments only (version freeze,
submission package, promote) and produces the receipt: per-file SHA-256, an
explicit grouped inventory (a missing declared item is visible, never silently
absent), and one root hash over the sorted "sha  path" lines so a reader can
tell whether the deposit they hold is the one the document was built from.
A report that needs the root hash QUOTES this receipt — it does not re-run
the hashing (the optional macros file exists precisely so the document quotes
the root from the same code path that computed it).

``verify_receipt`` re-derives trust ON DEMAND ONLY — see its docstring warning.

Ported from the proven run-local ``mkdeposit.py``
(runs/ref-free-seg-qa/deep_research-20260819T055022Z/tools/), generalized:
groups/paths are caller-supplied, paths are recorded relative to the manifest's
directory (so receipt + tree travel together), and the original declarations
are kept so verification can name added files, not only changed/missing ones.

Domain-general; stdlib only; never writes the vault.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

_CHUNK = 1 << 20
_MACROS_STAMP = "%% AUTO-GENERATED by tools/deposit_manifest.py -- do not hand-edit.\n"


@dataclass
class Manifest:
    """The release receipt: what the deposit contains and the hash that names it."""

    title: str
    author: str
    created_utc: str
    manifest_path: str
    root_sha256: str
    n_files: int
    total_bytes: int
    missing_declared_items: List[str] = field(default_factory=list)
    duplicate_paths_skipped: List[str] = field(default_factory=list)
    by_group: Dict[str, int] = field(default_factory=dict)
    declared_items: List[Dict[str, str]] = field(default_factory=list)
    receipt_macros_path: Optional[str] = None
    files: List[Dict[str, Any]] = field(default_factory=list)

    def to_payload(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ReceiptCheck:
    """Outcome of an on-demand receipt verification (changed / missing / added)."""

    manifest_path: str
    claimed_root_sha256: str
    n_files_listed: int
    changed: List[Dict[str, str]] = field(default_factory=list)
    missing: List[str] = field(default_factory=list)
    added: List[str] = field(default_factory=list)
    recomputed_root_sha256: Optional[str] = None
    root_matches: Optional[bool] = None
    notes: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not (self.changed or self.missing or self.added)

    def to_payload(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["ok"] = self.ok
        return payload


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(_CHUNK), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _store_path(target: Path, base: Path) -> str:
    """Record ``target`` relative to the manifest directory when possible (posix),
    absolute otherwise (e.g. a different drive) — the receipt must resolve alone."""
    try:
        return Path(os.path.relpath(str(target), str(base))).as_posix()
    except ValueError:  # different drive on Windows
        return target.resolve().as_posix()


def _expand_dir(directory: Path) -> List[Path]:
    return sorted(
        item for item in directory.rglob("*")
        if item.is_file() and "__pycache__" not in item.parts
    )


def _root_hash(entries: Sequence[Dict[str, Any]]) -> str:
    lines = "\n".join(f'{e["sha256"]}  {e["path"]}' for e in entries)
    return hashlib.sha256(lines.encode("utf-8")).hexdigest()


def build_manifest(
    groups: Dict[str, List[Path]],
    out_path: Path,
    *,
    author: str,
    title: str,
    macros_path: "Path | None" = None,
    created_utc: "str | None" = None,
) -> Manifest:
    """Hash the declared artifact set ONCE and write the receipt to ``out_path``.

    ``groups`` maps a group name to files and/or directories (directories are
    expanded recursively, ``__pycache__`` skipped). Declared items that do not
    exist are listed in ``missing_declared_items`` — visible, never silently
    absent. Entries are sorted by stored path, so the root hash is independent
    of group-dict ordering; the same overall file set always names the same
    root. The manifest file itself (and the macros file) are excluded from the
    set even when they sit inside a declared directory.

    ``macros_path``, when given, receives a stamped .tex defining
    ``\\depositRoot`` / ``\\depositRootFull`` / ``\\depositFiles`` so a document
    quotes the root hash from the same code path that computed it (never
    hand-transcribed). ``created_utc`` lets deterministic callers pin the
    receipt timestamp; default is now (UTC, ISO-8601).
    """
    out_path = Path(out_path)
    base = out_path.resolve().parent
    self_paths = {out_path.resolve()}
    if macros_path is not None:
        self_paths.add(Path(macros_path).resolve())

    entries: List[Dict[str, Any]] = []
    missing: List[str] = []
    duplicates: List[str] = []
    declared: List[Dict[str, str]] = []
    seen: set = set()

    def _add_file(group: str, file_path: Path) -> None:
        resolved = file_path.resolve()
        if resolved in self_paths:
            return
        stored = _store_path(resolved, base)
        if resolved in seen:
            duplicates.append(stored)
            return
        seen.add(resolved)
        entries.append(
            {
                "group": group,
                "path": stored,
                "bytes": resolved.stat().st_size,
                "sha256": _sha256_file(resolved),
            }
        )

    for group, items in groups.items():
        for item in items:
            p = Path(item)
            if p.is_dir():
                declared.append({"group": group, "path": _store_path(p.resolve(), base), "kind": "dir"})
                for file_path in _expand_dir(p):
                    _add_file(group, file_path)
            elif p.is_file():
                declared.append({"group": group, "path": _store_path(p.resolve(), base), "kind": "file"})
                _add_file(group, p)
            else:
                declared.append({"group": group, "path": str(p), "kind": "missing"})
                missing.append(str(p))

    entries.sort(key=lambda e: e["path"])
    root = _root_hash(entries)

    macros_stored: Optional[str] = None
    if macros_path is not None:
        macros_path = Path(macros_path)
        macros_path.parent.mkdir(parents=True, exist_ok=True)
        macros_path.write_text(
            _MACROS_STAMP
            + f"\\newcommand{{\\depositRoot}}{{{root[:16]}}}\n"
            + f"\\newcommand{{\\depositRootFull}}{{{root}}}\n"
            + f"\\newcommand{{\\depositFiles}}{{{len(entries)}}}\n",
            encoding="utf-8",
        )
        macros_stored = _store_path(macros_path.resolve(), base)

    manifest = Manifest(
        title=title,
        author=author,
        created_utc=created_utc or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        manifest_path=str(out_path),
        root_sha256=root,
        n_files=len(entries),
        total_bytes=sum(e["bytes"] for e in entries),
        missing_declared_items=missing,
        duplicate_paths_skipped=duplicates,
        by_group={g: sum(1 for e in entries if e["group"] == g) for g in groups},
        declared_items=declared,
        receipt_macros_path=macros_stored,
        files=entries,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(manifest.to_payload(), ensure_ascii=False, indent=1), encoding="utf-8"
    )
    return manifest


def verify_receipt(manifest_path: Path) -> ReceiptCheck:
    """Re-hash the deposit against its receipt ON DEMAND; report changed/missing/added.

    POLICY WARNING (TU-2 / catalog E1): routine or scheduled re-verification is a
    policy violation. A receipt is invalidated by exactly one thing — a change to
    the artifact set it covers — never by the passage of time. This function
    exists for release moments (re-freezing a changed set) and dispute
    resolution (a reader or reviewer questions deposit identity), not for
    per-report or per-build habit. If you find yourself calling it on a
    schedule, the artifact set is not what changed — the policy did.

    ``added`` can only be detected for items declared as directories at build
    time (their expansion is re-derivable); a foreign manifest without
    ``declared_items`` gets a note instead of a silent skip.
    """
    manifest_path = Path(manifest_path)
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    base = manifest_path.resolve().parent
    listed = data.get("files", [])
    check = ReceiptCheck(
        manifest_path=str(manifest_path),
        claimed_root_sha256=data.get("root_sha256", ""),
        n_files_listed=len(listed),
    )

    def _resolve(stored: str) -> Path:
        p = Path(stored)
        return p if p.is_absolute() else (base / p)

    listed_paths = set()
    current_entries: List[Dict[str, Any]] = []
    for row in listed:
        stored = row.get("path", "")
        expected = row.get("sha256", "")
        target = _resolve(stored)
        listed_paths.add(target.resolve())
        if not target.is_file():
            check.missing.append(stored)
            continue
        actual = _sha256_file(target)
        current_entries.append({"path": stored, "sha256": actual})
        if actual != expected:
            check.changed.append({"path": stored, "expected": expected, "actual": actual})

    declared = data.get("declared_items")
    if declared is None:
        check.notes.append(
            "manifest carries no declared_items — added-file detection unavailable"
        )
    else:
        exclusions = {manifest_path.resolve()}
        macros_stored = data.get("receipt_macros_path")
        if macros_stored:
            exclusions.add(_resolve(macros_stored).resolve())
        for item in declared:
            if item.get("kind") != "dir":
                continue
            directory = _resolve(item.get("path", ""))
            if not directory.is_dir():
                continue  # the whole directory going missing already shows as missing files
            for file_path in _expand_dir(directory):
                resolved = file_path.resolve()
                if resolved in exclusions or resolved in listed_paths:
                    continue
                check.added.append(_store_path(resolved, base))
        check.added = sorted(set(check.added))

    if not check.missing:
        current_entries.sort(key=lambda e: e["path"])
        check.recomputed_root_sha256 = _root_hash(current_entries)
        check.root_matches = check.recomputed_root_sha256 == check.claimed_root_sha256
    else:
        check.notes.append("root not recomputed: listed files are missing")
    return check
